<?php

/**
 * @file
 * Contains the finder.module.
 */

/**
 * Implements hook_theme().
 */
function finder_theme($existing, $type, $theme, $path) {
  return [
    'finder' => [
      'variables' => [],
      'template' => 'finder',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function finder_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  switch ($key) {
    case 'complete_form':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      // Removed from following array: '@title' => $params['node_title'].
      $message['subject'] = t('Finder email', [], $options);
      $message['body'][] = $params['message'];
      break;
  }
}

/**
 * This gets the configuration page to show up.
 */
function finder_menu() {
  $items = [];
  $items['admin/config/content/finder'] = [
    'title' => 'Finder',
    'description' => 'Configuration for Finder module',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['finder_admin_settings'],
    'access arguments' => ['access administration pages'],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;

}
